### PR TITLE
Chore setup linter

### PR DESCRIPTION
**Pull request by cahnory**
Before applying the changes requested by the linter, I wanted to make sure that:

1. The use of a linter is desired.
2. The defined rules are suitable for you.

Regarding point 2, one of the rules that you would likely want to modify is **func-style**. The rest are either autofixable, relatively trivial (prefer `+= 1` 1 over `++`), or a best practice (enforce `===`).

### CODE REVIEW

**Comment by Nicolas-PredictaLab** [comment]
Hey, thanks @cahnory, I'll try to have a look at it as soon as possible.

**Comment by Nicolas-PredictaLab** [comment]
Ok I've reviewed it and ... why not :D Thoses rules seems stricter than how I usually code but yeah, why not, I'm curious to see how it can goes followings all those rules. 
I've also tried the autofix and yes it seems to carry about 70% of the changes, but was pretty perplex about the remaining ones especially where suggest fixes are triggering another error, fixed by previous version, etc etc :D

So yeah, I'm ok to review them all once it's done, thanks for your time.

**Comment by Nicolas-PredictaLab** [comment]
Oh and for func-style, `"func-style": ["error", "expression", { "allowArrowFunctions": true }],` seems good

**Comment by cahnory** [comment]
> Ok I've reviewed it and ... why not :D Thoses rules seems stricter than how I usually code but yeah, why not, I'm curious to see how it can goes followings all those rules. I've also tried the autofix and yes it seems to carry about 70% of the changes, but was pretty perplex about the remaining ones especially where suggest fixes are triggering another error, fixed by previous version, etc etc :D
> 
> So yeah, I'm ok to review them all once it's done, thanks for your time.

I'll be away from home for the next 7 days, but I can take care of applying the fixes when I get back. Once done, it will be easier to follow the rules. Also, if you come across a rule you think is wrong, you can always change it.


> Oh and for func-style, `"func-style": ["error", "expression", { "allowArrowFunctions": true }],` seems good

👍

**Pull request closed without merging**
